<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="3" total="7" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Before SUite Executed]]>
    </line>
    <line>
      <![CDATA[HI]]>
    </line>
    <line>
      <![CDATA[Photo is taken]]>
    </line>
    <line>
      <![CDATA[Title is Matching :actiTIME - Enter Time-Track]]>
    </line>
    <line>
      <![CDATA[Title is Matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Element is Present]]>
    </line>
    <line>
      <![CDATA[Element is NOT Present]]>
    </line>
    <line>
      <![CDATA[Photo is taken]]>
    </line>
    <line>
      <![CDATA[Photo is taken]]>
    </line>
  </reporter-output>
  <suite name="AutoamtionSuite" duration-ms="40188" started-at="2017-07-15T10:31:38Z" finished-at="2017-07-15T10:32:18Z">
    <groups>
    </groups>
    <test name="RegressionTest" duration-ms="40188" started-at="2017-07-15T10:31:38Z" finished-at="2017-07-15T10:32:18Z">
      <class name="com.ipe2.tests.VerifyVersion">
        <test-method status="PASS" signature="openApp()[pri:0, instance:com.ipe2.tests.VerifyVersion@57fffcd7]" name="openApp" is-config="true" duration-ms="4568" started-at="2017-07-15T16:02:10Z" finished-at="2017-07-15T16:02:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testVerifyVersion()[pri:3, instance:com.ipe2.tests.VerifyVersion@57fffcd7]" name="testVerifyVersion" duration-ms="2081" started-at="2017-07-15T16:02:14Z" finished-at="2017-07-15T16:02:17Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <div class="popup_menu_label">...</div> is not clickable at point (821, 68). Other element would receive the click: <div id="preInsertedTransformedMoireId" class="transformedMoireClass" style="transition: opacity 600ms ease-in-out; opacity: 0;"></div>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 110 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-TDF5CHD', ip: '100.113.57.88', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\lava\AppData\Local\Temp\scoped_dir13672_5358}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 228fd478d29048ddf16121ac092dbd14]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <div class="popup_menu_label">...</div> is not clickable at point (821, 68). Other element would receive the click: <div id="preInsertedTransformedMoireId" class="transformedMoireClass" style="transition: opacity 600ms ease-in-out; opacity: 0;"></div>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 110 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-TDF5CHD', ip: '100.113.57.88', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\lava\AppData\Local\Temp\scoped_dir13672_5358}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 228fd478d29048ddf16121ac092dbd14
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy10.click(Unknown Source)
	at com.ipe2.pages.EnterTimeTrackPage.clickSettings(EnterTimeTrackPage.java:32)
	at com.ipe2.tests.VerifyVersion.testVerifyVersion(VerifyVersion.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
            <line>
              <![CDATA[Photo is taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- testVerifyVersion -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.ipe2.tests.VerifyVersion@57fffcd7]" name="closeApp" is-config="true" duration-ms="897" started-at="2017-07-15T16:02:17Z" finished-at="2017-07-15T16:02:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.ipe2.tests.VerifyVersion -->
      <class name="com.ipe2.tests.Demo">
        <test-method status="PASS" signature="setDriverPath()[pri:0, instance:com.ipe2.tests.Demo@13deb50e]" name="setDriverPath" is-config="true" duration-ms="19" started-at="2017-07-15T16:01:38Z" finished-at="2017-07-15T16:01:38Z">
          <reporter-output>
            <line>
              <![CDATA[Before SUite Executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- setDriverPath -->
        <test-method status="PASS" signature="openApp()[pri:0, instance:com.ipe2.tests.Demo@13deb50e]" name="openApp" is-config="true" duration-ms="7640" started-at="2017-07-15T16:01:38Z" finished-at="2017-07-15T16:01:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="SampleTest()[pri:0, instance:com.ipe2.tests.Demo@13deb50e]" name="SampleTest" duration-ms="13" started-at="2017-07-15T16:01:45Z" finished-at="2017-07-15T16:01:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.ipe2.tests.Demo.SampleTest(Demo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HI]]>
            </line>
            <line>
              <![CDATA[Photo is taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- SampleTest -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.ipe2.tests.Demo@13deb50e]" name="closeApp" is-config="true" duration-ms="1231" started-at="2017-07-15T16:01:46Z" finished-at="2017-07-15T16:01:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.ipe2.tests.Demo -->
      <class name="com.ipe2.tests.ValidLoginLogout">
        <test-method status="PASS" signature="openApp()[pri:0, instance:com.ipe2.tests.ValidLoginLogout@3abbfa04]" name="openApp" is-config="true" duration-ms="5044" started-at="2017-07-15T16:01:47Z" finished-at="2017-07-15T16:01:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="testValidLoginLogout()[pri:1, instance:com.ipe2.tests.ValidLoginLogout@3abbfa04]" name="testValidLoginLogout" duration-ms="8546" started-at="2017-07-15T16:01:52Z" finished-at="2017-07-15T16:02:01Z">
          <reporter-output>
            <line>
              <![CDATA[Title is Matching :actiTIME - Enter Time-Track]]>
            </line>
            <line>
              <![CDATA[Title is Matching :actiTIME - Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLoginLogout -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.ipe2.tests.ValidLoginLogout@3abbfa04]" name="closeApp" is-config="true" duration-ms="830" started-at="2017-07-15T16:02:01Z" finished-at="2017-07-15T16:02:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.ipe2.tests.ValidLoginLogout -->
      <class name="com.ipe2.tests.InvalidLogin">
        <test-method status="PASS" signature="openApp()[pri:0, instance:com.ipe2.tests.InvalidLogin@239963d8]" name="openApp" is-config="true" duration-ms="4594" started-at="2017-07-15T16:02:02Z" finished-at="2017-07-15T16:02:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testInvalidLogin()[pri:2, instance:com.ipe2.tests.InvalidLogin@239963d8]" name="testInvalidLogin" duration-ms="2233" started-at="2017-07-15T16:02:06Z" finished-at="2017-07-15T16:02:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at generics.BasePage.verifyElementIsPresent(BasePage.java:46)
	at com.ipe2.pages.LoginPage.verifyErrMsgIsDisplayed(LoginPage.java:48)
	at com.ipe2.tests.InvalidLogin.testInvalidLogin(InvalidLogin.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Element is Present]]>
            </line>
            <line>
              <![CDATA[Element is NOT Present]]>
            </line>
            <line>
              <![CDATA[Photo is taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.ipe2.tests.InvalidLogin@239963d8]" name="closeApp" is-config="true" duration-ms="1001" started-at="2017-07-15T16:02:09Z" finished-at="2017-07-15T16:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.ipe2.tests.InvalidLogin -->
    </test> <!-- RegressionTest -->
  </suite> <!-- AutoamtionSuite -->
</testng-results>
